### ISSUE TITLE
Problems deploying application on a server

### ISSUE THREAD

**Issue by mesabg** [minhajuddin/simpleformgo#2]
Hey there ! 
I'm having some troubles trying to deploy your app in my production server, I can do it locally with no problems but can you give me an explanation about how to do it in a production server ? . I just have FTP access and mysql database (I already change db.go to adap it)

I appreciate your answer, thanks !

**Comment by minhajuddin** [comment]
This needs to be run using on a postgresql database. You need to compile this using a proper go setup and then you can ftp the binary to your server and start it up.

**Comment by mesabg** [comment]
It compiles simpleform (Binary) and if I run it in my localhost, it works with no problems. The problem is that I cannot use an ssh to start the script on the server I just have ftp. Do you have any solution for this ?
